#!/bin/sh
#Author: Fernando Sanchez (fernando at plumgrid dot com)
#(c)2016 Fernando Sanchez and PLUMgrid inc.
#Resource file including all configuration variables required for the Openstack NFV vCPE demo.
#Most installations should only need changing the first section to adapt to external connectivity and
#Controller IP location.
#This assumes that the authentication Endpoint types is 'publicURL'.
#For installations where it is 'internalURL' the Openstack section may need to be copied from "openrc"

############################################################################
############ PARAMETERS TO BE ADJUSTED FOR NEW INSTALLATIONS ###############
############################################################################

export ADMIN_NAME='admin'
export ADMIN_PASSWORD='changeme' 		#Orangebox=???
export KEYSTONE_IP=20.0.0.2 			#Orangebox=???
export PHYSICAL_PORT='stove+enp1s0f2'		#Orangebox='node00vm1ob44+eth1'
export EXTERNAL_NET_TYPE='flat'			#could be flat
export EXTERNAL_NET_VLAN_ID=0			#VLAN_ID
export EXTERNAL_NET_CIDR=192.168.99.0/24 	#Orangebox=172.27.46.0/23
export EXTERNAL_NET_GW=192.168.99.254 		#Orangebox=172.27.47.254
export EXTERNAL_NET_DNS=192.168.99.254		#Orangebox=172.27.47.254
export FLOATINGIP_START=192.168.99.231		#Orangebox=172.27.46.50
export FLOATINGIP_END=192.168.99.240		#Orangebox=172.27.46.253
export ENDPOINT_TYPE=''				#'' 'publicURL' or 'internalURL' depending on openstack deployemnt
export REGION_NAME=''				#typical values are '', 'Openstack' or 'RegionOne'

############################################################################
############################################################################
############################################################################

#vRouter appliance
export VNF_flavor='m1.small'
export VNF_1_name='pg-nfv_vRouter'
export VNF_1_image='vRouter'
export VNF_1_file='./VYOS-NFV_demo.qcow2?dl=0'
export VNF_1_location='https://www.dropbox.com/s/zuz0y7jse4t7iec/VYOS-NFV_demo.qcow2?dl=0'
export VNF_1_ip_1=172.16.1.254
export VNF_1_ip_2=172.16.2.2

#WebServer appliance
export VNF_2_name='pg-nfv_webServer'
export VNF_2_image='webServer'
export VNF_2_file='./webServer-NFV_demo.qcow2?dl=0'
export VNF_2_location='https://www.dropbox.com/s/0dp7gyvmd0awmlb/webServer-NFV_demo.qcow2?dl=0'
export VNF_2_ip_1=172.16.1.100
export VNF_2_ip_2=172.16.2.100

#WAN net
export WAN_net_name='WAN_net'
export WAN_net_type=$EXTERNAL_NET_TYPE
export WAN_net_vlan_id=$EXTERNAL_NET_VLAN_ID
export WAN_net_physical_port=$PHYSICAL_PORT
export WAN_subnet_name='WAN_net'
export WAN_subnet_cidr=$EXTERNAL_NET_CIDR
export WAN_subnet_gw=$EXTERNAL_NET_GW
export WAN_subnet_dns=$EXTERNAL_NET_DNS
export WAN_subnet_dhcp_start=$FLOATINGIP_START
export WAN_subnet_dhcp_end=$FLOATINGIP_END


#openstack credentials
export OS_NO_CACHE='true'
export OS_TENANT_NAME=$ADMIN_NAME
export OS_PROJECT_NAME=$ADMIN_NAME
export OS_USERNAME=$ADMIN_NAME
export OS_PASSWORD=$ADMIN_PASSWORD
export OS_AUTH_URL='http://'$KEYSTONE_IP':5000/v2.0/'
export OS_AUTH_STRATEGY='keystone'
export OS_REGION_NAME=$REGION_NAME
export CINDER_ENDPOINT_TYPE=$ENDPOINT_TYPE
export GLANCE_ENDPOINT_TYPE=$ENDPOINT_TYPE
export KEYSTONE_ENDPOINT_TYPE=$ENDPOINT_TYPE
export NOVA_ENDPOINT_TYPE=$ENDPOINT_TYPE
export NEUTRON_ENDPOINT_TYPE=$ENDPOINT_TYPE

#NFV tenant
export NFV_tenant_name='NFV'

#NFV net_out _ from WAN to NFV
export NFV_net_out_name='NFV_net_out'
export NFV_subnet_out_name='NFV_subnet_out'
export NFV_subnet_out_cidr=172.16.1.0/24
export NFV_subnet_out_gw=172.16.1.1
export NFV_subnet_out_dhcp_range_start=172.16.1.50
export NFV_subnet_out_dhcp_range_end=172.16.1.253

#rtr_out _ from WAN to NFV
export rtr_out_name='zPG_dynamic_rtr_out'

#export rtr_out_ip_WAN=dhcp
export rtr_out_ip_NFV=$NFV_subnet_out_1_gw

#NFV net_in _ from NFV to METRO
export NFV_net_in_name='NFV_net_in'
export NFV_subnet_in_name='NFV_subnet_in'
export NFV_subnet_in_cidr=172.16.2.0/24
export NFV_subnet_in_gw=172.16.2.254
export NFV_subnet_in_dhcp_range_start=172.16.2.50
export NFV_subnet_in_dhcp_range_end=172.16.2.253

#METRO subnet _ from METRO to CPE
export METRO_net_name='METRO_net'
export METRO_subnet_name='METRO_subnet'
export METRO_subnet_cidr=172.16.254.0/24
export METRO_subnet_gw=172.16.254.1

#router_in _ from NFV to METRO
export rtr_in_name='zPG_dynamic_rtr_in'
export rtr_in_ip_nfv=172.16.2.254
export rtr_in_ip_metro=$METRO_subnet_254_gw

export member_role_name='_member_'
export VNF_1_port_1_id=dd934aa8-dda4-474a-a315-bdf39170cbda
export VNF_1_port_2_id=5588b454-860e-4d00-8a5a-fca0c6f6419d
export VNF_2_port_1_id=73717dfe-cfa3-488d-ac2f-3137fcde1607
export VNF_2_port_2_id=a272e72d-2177-4b64-a9b6-f5f9aeb7325f
export default_secgroup_id=af49e300-8924-4146-8e6b-47e4ca74fd18
export VNF_1_port_1_id=6954cd3d-51fa-4035-9ea7-eb6536e8bf5a
export VNF_1_port_2_id=2d3f6b65-e6a5-4afc-ac30-3d8906477313
export VNF_2_port_1_id=b423b578-0500-4a1c-8a36-cdc5e59265b4
export VNF_2_port_2_id=e9b38979-f5c0-4f2e-bc50-f8493d271895
export default_secgroup_id=801ec0ac-1729-4da5-8406-fa680a535979
export VNF_1_port_1_id=ca47c316-82af-45d0-87f6-17eeaad5aa70
export VNF_1_port_2_id=df897785-1339-4b38-89e3-18c8b2aac385
export VNF_2_port_1_id=445c4b7c-efc8-4438-94df-72067c9b1b3d
export VNF_2_port_2_id=2c99cd22-1756-498d-b231-f9e0c3dc80fb
export default_secgroup_id=4e192e2b-a0e7-4fee-8039-6d0898aa7d86
export VNF_1_port_1_id=721efc2f-e29b-4d4e-ae73-ed7f3c945e60
export VNF_1_port_2_id=8f6793f7-dba2-4def-aabe-14225e0bf3c3
export VNF_2_port_1_id=54440030-8505-4cb2-9ac8-b97f6c2bbc6e
export VNF_2_port_2_id=04f4401b-3972-49c7-8a94-9434a79425f0
export default_secgroup_id=fff65cc1-eef5-469a-9788-1513ffb9671f
